### ISSUE TITLE
can't install on codium

### ISSUE THREAD

**Issue by ralyodio** [mojolicious/vscode-mojo.js#1]
ext install kraih.javascript-tmpl-support

this plugin doesn't exist in codium

**Comment by kraih** [comment]
I don't know what that means. This is a VSCode plugin. https://marketplace.visualstudio.com/items?itemName=kraih.javascript-tmpl-support

**Comment by jberger** [comment]
Is that referring to this? https://github.com/VSCodium/vscodium#why-does-this-exist I've never seen it before but it is interesting regardless

**Comment by kraih** [comment]
Published. https://open-vsx.org/extension/kraih/javascript-tmpl-support
